import { PrismaClient, UserRole, UserStatus, WoStatus, WoType } from '@prisma/client';
import { FieldExceptionService } from './field-exception.service';

const prisma=new PrismaClient();const service=new FieldExceptionService(prisma as any);const tag=`field-ex-db-${Date.now()}`;
function ok(name:string,value:unknown){if(!value)throw new Error(`FAIL: ${name}`);console.log(`PASS: ${name}`)}
async function fixture(suffix:string){const team=await prisma.team.create({data:{name:`${tag}-${suffix}-team`}});const manager=await prisma.user.create({data:{role:UserRole.JOB_CONTROLLER,name:`${tag}-${suffix}-manager`,email:`${tag}-${suffix}-manager@example.invalid`,status:UserStatus.ONLINE}});const tech=await prisma.user.create({data:{role:UserRole.TECHNICIAN,teamId:team.id,name:`${tag}-${suffix}-tech`,email:`${tag}-${suffix}-tech@example.invalid`,status:UserStatus.WORKING}});const sub=await prisma.subscriber.create({data:{accountNumber:`${tag}-${suffix}-acct`,name:'Exception E2E Subscriber',address:'Exception E2E Address',contactNumber:'0',plan:'E2E'}});const wo=await prisma.workOrder.create({data:{woNumber:`${tag}-${suffix}-wo`,type:WoType.REPAIR,status:WoStatus.WORKING,subscriberId:sub.id,createdBy:manager.id}});await prisma.assignment.create({data:{workOrderId:wo.id,teamId:team.id,assignedBy:manager.id}});const execution=await prisma.jobExecution.create({data:{workOrderId:wo.id,technicianId:tech.id,status:WoStatus.WORKING}});return{team,manager,tech,wo,execution}}
async function main(){
 const a=await fixture('hold');const reported=await service.report(a.wo.id,a.tech.id,{reason:'UNSAFE_CONDITION',notes:'Live electrical hazard',lat:14.3,lng:120.9});ok('report creates pending exception',reported.exception.status==='PENDING');ok('report places WO ON_HOLD',(await prisma.workOrder.findUnique({where:{id:a.wo.id}}))?.status===WoStatus.ON_HOLD);ok('report returns technician AVAILABLE',(await prisma.user.findUnique({where:{id:a.tech.id}}))?.status===UserStatus.AVAILABLE);
 const kept=await service.review(reported.exception.id,a.manager.id,UserRole.JOB_CONTROLLER,{resolution:'KEEP_ON_HOLD',note:'Await site safety clearance'});ok('KEEP_ON_HOLD remains pending',kept.pending===true&&(await prisma.fieldException.findUnique({where:{id:reported.exception.id}}))?.status==='PENDING');
 const resumed=await service.review(reported.exception.id,a.manager.id,UserRole.JOB_CONTROLLER,{resolution:'RESUME',note:'Site cleared'});ok('RESUME restores WORKING',resumed.workOrderStatus===WoStatus.WORKING&&(await prisma.user.findUnique({where:{id:a.tech.id}}))?.status===UserStatus.WORKING);
 const b=await fixture('return');const br=await service.report(b.wo.id,b.tech.id,{reason:'CUSTOMER_UNAVAILABLE'});await service.review(br.exception.id,b.manager.id,UserRole.JOB_CONTROLLER,{resolution:'RETURN_TO_ASSIGNED',note:'Dispatch later'});ok('RETURN_TO_ASSIGNED closes execution',(await prisma.jobExecution.findUnique({where:{id:b.execution.id}}))?.completedAt!=null);ok('RETURN_TO_ASSIGNED changes WO',(await prisma.workOrder.findUnique({where:{id:b.wo.id}}))?.status===WoStatus.ASSIGNED);
 const c=await fixture('cancel');const cr=await service.report(c.wo.id,c.tech.id,{reason:'SITE_INACCESSIBLE'});await service.review(cr.exception.id,c.manager.id,UserRole.JOB_CONTROLLER,{resolution:'CANCEL',note:'Access permanently blocked'});ok('CANCEL closes execution and WO',(await prisma.jobExecution.findUnique({where:{id:c.execution.id}}))?.completedAt!=null&&(await prisma.workOrder.findUnique({where:{id:c.wo.id}}))?.status===WoStatus.CANCELLED);
 const d=await fixture('race');const dr=await service.report(d.wo.id,d.tech.id,{reason:'RESCHEDULE_REQUESTED'});const race=await Promise.allSettled([service.review(dr.exception.id,d.manager.id,UserRole.JOB_CONTROLLER,{resolution:'RETURN_TO_ASSIGNED',note:'First'}),service.review(dr.exception.id,d.manager.id,UserRole.JOB_CONTROLLER,{resolution:'CANCEL',note:'Second review'})]);ok('concurrent management review accepts exactly one',race.filter(x=>x.status==='fulfilled').length===1);
 const e=await fixture('conflict');const er=await service.report(e.wo.id,e.tech.id,{reason:'NEEDS_CONTROLLER_SUPPORT',notes:'Need controller assistance'});const otherSub=await prisma.subscriber.create({data:{accountNumber:`${tag}-other-acct`,name:'Other',address:'Other',contactNumber:'0',plan:'E2E'}});const otherWo=await prisma.workOrder.create({data:{woNumber:`${tag}-other-wo`,type:WoType.REPAIR,status:WoStatus.WORKING,subscriberId:otherSub.id,createdBy:e.manager.id}});await prisma.jobExecution.create({data:{workOrderId:otherWo.id,technicianId:e.tech.id,status:WoStatus.WORKING}});let conflict=false;try{await service.review(er.exception.id,e.manager.id,UserRole.JOB_CONTROLLER,{resolution:'RESUME'})}catch{conflict=true}ok('RESUME blocked when technician has another active execution',conflict);ok('blocked RESUME leaves original exception pending',(await prisma.fieldException.findUnique({where:{id:er.exception.id}}))?.status==='PENDING');
 const audits=await prisma.auditLog.findMany({where:{workOrderId:a.wo.id}});ok('exception lifecycle audit chain persisted',['FIELD_EXCEPTION_REPORTED','FIELD_EXCEPTION_KEPT_ON_HOLD','FIELD_EXCEPTION_REVIEWED'].every(x=>audits.some(a=>a.action===x)));
 console.log('Database-backed field exception lifecycle gate passed.');
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>prisma.$disconnect());
