'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { apiJson, clearSession, downloadAuthenticated, loadSession, login, Session } from '../lib/api';

type WorkOrder={id:string;woNumber:string;type:string;status:string;subscriberName?:string;subscriber?:{name?:string;address?:string};assignments?:{teamId:string}[]};
type Technician={id:string;name?:string;status?:string;lastLat?:number|null;lastLng?:number|null;lastLocationAt?:string|null};type Team={id:string;name:string;activeTechnicians:number;technicians:Technician[]};
type FieldException={id:string;workOrderId:string;technicianId:string;reason:string;notes?:string|null;lat?:number|null;lng?:number|null;reportedAt:string;status:string;workOrder:WorkOrder};type Resolution='RESUME'|'KEEP_ON_HOLD'|'RETURN_TO_ASSIGNED'|'CANCEL';
const RESOLUTIONS:{value:Resolution;label:string;help:string;danger?:boolean}[]=[{value:'RESUME',label:'Resume Work',help:'Return the same work order to WORKING and the reporting technician to WORKING.'},{value:'KEEP_ON_HOLD',label:'Keep On Hold',help:'Close this review while keeping the work order ON_HOLD. A management note is required.'},{value:'RETURN_TO_ASSIGNED',label:'Return To Assigned',help:'End the current execution and return the work order to ASSIGNED for controlled dispatch.'},{value:'CANCEL',label:'Cancel Work Order',help:'End the current execution and cancel the work order. A management note is required.',danger:true}];
export default function ManagementPortal(){
 const[session,setSession]=useState<Session|null>(null),[booting,setBooting]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[range,setRange]=useState('monthly');
 const[report,setReport]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null),[network,setNetwork]=useState<any>(null),[workOrders,setWorkOrders]=useState<WorkOrder[]>([]),[teams,setTeams]=useState<Team[]>([]),[technicianId,setTechnicianId]=useState(''),[route,setRoute]=useState<any>(null),[exceptions,setExceptions]=useState<FieldException[]>([]);
 const[selectedWoId,setSelectedWoId]=useState(''),[selectedTeamId,setSelectedTeamId]=useState(''),[expectedTeamId,setExpectedTeamId]=useState<string|null>(null),[nearby,setNearby]=useState<any[]>([]),[smartNext,setSmartNext]=useState<any>(null),[reviewing,setReviewing]=useState<FieldException|null>(null),[resolution,setResolution]=useState<Resolution>('RESUME'),[reviewNote,setReviewNote]=useState('');
 useEffect(()=>{setSession(loadSession());setBooting(false)},[]);
 async function refresh(active:Session,selectedRange=range){setError('');try{const[r,a,w,n,t,x]=await Promise.all([apiJson(`/reports/summary?range=${selectedRange}`,{},active),apiJson(`/phase4/analytics/advanced?range=${selectedRange}`,{},active),apiJson('/work-orders',{},active),apiJson('/phase4/network/health',{},active),apiJson('/work-orders/dispatch/teams',{},active),apiJson('/work-orders/exceptions/pending',{},active)]);setReport(r);setAnalytics(a);setWorkOrders(w.data||[]);setNetwork(n);setTeams(t.teams||[]);setExceptions(x.data||[])}catch(e:any){setError(e.message||'Unable to load management data');if(e.message==='Session expired'||e.message==='AUTH_REQUIRED')setSession(null)}}
 useEffect(()=>{if(session)refresh(session,range)},[session,range]);
 async function submitLogin(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await login(email,password);setSession(s);setPassword('')}catch(e:any){setError(e.message||'Login failed')}finally{setBusy(false)}}function logout(){clearSession();setSession(null);setReport(null);setWorkOrders([]);setTeams([]);setExceptions([])}
 const technicians=useMemo(()=>teams.flatMap(t=>t.technicians||[]).filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i),[teams]);const selectedWo=workOrders.find(w=>w.id===selectedWoId);
 async function assign(){if(!selectedWoId||!selectedTeamId)return;setBusy(true);setError('');setNotice('');try{const result=await apiJson(`/work-orders/${selectedWoId}/assign`,{method:'POST',body:JSON.stringify({teamId:selectedTeamId,expectedTeamId})},session);setNotice(result.idempotent?'Assignment already current. No duplicate change was made.':selectedWo?.status==='ASSIGNED'?'Work order reassigned. Previous assignment was replaced and audited.':'Work order assigned and audited.');await refresh(session!,range)}catch(e:any){setError(e.message||'Assignment failed')}finally{setBusy(false)}}
 async function reviewException(){if(!reviewing||!session||busy)return;const needsNote=resolution==='KEEP_ON_HOLD'||resolution==='CANCEL';if(needsNote&&reviewNote.trim().length<5){setError('A management note of at least 5 characters is required for this resolution.');return}setBusy(true);setError('');setNotice('');try{const result=await apiJson(`/work-orders/exceptions/${encodeURIComponent(reviewing.id)}/review`,{method:'POST',body:JSON.stringify({resolution,note:reviewNote.trim()||undefined})},session);setNotice(`${reviewing.workOrder?.woNumber||'Work order'} reviewed: ${resolution.replaceAll('_',' ')} → ${result.workOrderStatus}. The action was recorded in the audit trail.`);setReviewing(null);setReviewNote('');setResolution('RESUME');await refresh(session,range)}catch(e:any){setError(e.message||'Field exception review failed. Refresh before retrying; another manager may already have reviewed it.');await refresh(session,range).catch(()=>{})}finally{setBusy(false)}}
 async function findNearby(){const tech=technicians.find(t=>t.id===technicianId);if(!tech||tech.lastLat==null||tech.lastLng==null){setError('Selected technician has no usable last-known location.');return}setBusy(true);setError('');try{const data=await apiJson(`/work-orders/nearby?lat=${tech.lastLat}&lng=${tech.lastLng}&radius=3000`,{},session);setNearby(data||[])}catch(e:any){setError(e.message||'Nearby lookup failed')}finally{setBusy(false)}}async function suggestNext(){const tech=technicians.find(t=>t.id===technicianId);if(!tech||tech.lastLat==null||tech.lastLng==null){setError('Selected technician has no usable last-known location.');return}setBusy(true);setError('');try{setSmartNext(await apiJson(`/work-orders/smart-next?technicianId=${encodeURIComponent(tech.id)}&lat=${tech.lastLat}&lng=${tech.lastLng}`,{},session))}catch(e:any){setError(e.message||'Smart Next failed')}finally{setBusy(false)}}async function optimizeRoute(){if(!technicianId){setError('Select a technician first.');return}setBusy(true);setError('');try{setRoute(await apiJson(`/phase4/route/optimize?technicianId=${encodeURIComponent(technicianId)}&date=${new Date().toISOString().slice(0,10)}`,{},session))}catch(e:any){setError(e.message||'Route optimization failed')}finally{setBusy(false)}}
 if(booting)return <Shell><div className="wfm-panel">Loading secure management portal…</div></Shell>;
 if(!session)return <Shell><div className="wfm-panel" style={{maxWidth:430,margin:'8vh auto'}}><div className="wfm-eyebrow">SECURE MANAGEMENT ACCESS</div><h1 style={{marginBottom:4}}>FiberBlaze WFM</h1><p className="wfm-copy">Management Portal • Authorized access only</p><form onSubmit={submitLogin} style={{display:'grid',gap:12}}><input required type="email" placeholder="Work email" value={email} onChange={e=>setEmail(e.target.value)}/><input required type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="wfm-alert">{error}</div>}<button disabled={busy} className="wfm-primary-btn">{busy?'Signing in…':'Sign in'}</button></form><p className="wfm-copy">Job Controller, Supervisor, and Administrator accounts only.</p></div></Shell>;
 return <Shell><div className="wfm-page-head"><div><div className="wfm-eyebrow">OPERATIONS COMMAND CENTER</div><h1>Command Center</h1><p>Authenticated field operations control • {session.user.role}</p></div><div className="wfm-head-actions"><span className="wfm-control-pill">{session.user.name||session.user.email}</span><button onClick={logout} className="wfm-secondary-btn">Sign out</button></div></div>{error&&<div className="wfm-alert">{error}</div>}{notice&&<div className="wfm-info">{notice}</div>}
 <div className="wfm-toolbar">{['daily','weekly','monthly'].map(r=><button key={r} onClick={()=>setRange(r)} className={range===r?'wfm-primary-btn':'wfm-secondary-btn'}>{r.toUpperCase()}</button>)}<button onClick={()=>downloadAuthenticated(`/reports/export?format=excel&range=${range}`,`fiberblaze-${range}.xlsx`,session)} className="wfm-secondary-btn">Export Excel</button><button onClick={()=>window.print()} className="wfm-secondary-btn">Print</button></div>
 <section className="wfm-kpis"><Metric label="Total WOs" value={report?.totals?.total??0}/><Metric label="Completed" value={report?.totals?.completed??0}/><Metric label="FB-Issue" value={report?.totals?.fbIssue??0}/><Metric label="Pending Field Issues" value={exceptions.length}/><Metric label="Network Health" value={network?.status||'—'}/></section>
 <section className="wfm-panel"><div className="wfm-section-title"><div><div className="wfm-eyebrow">CONTROLLED FIELD REVIEW</div><h3>Field Exception Review Center</h3><p className="wfm-copy">Technician-reported blockers remain ON_HOLD until management makes an explicit, audited decision.</p></div><button disabled={busy} onClick={()=>refresh(session,range)} className="wfm-secondary-btn">Refresh Issues</button></div>{!exceptions.length?<div className="wfm-empty">No pending field exceptions.</div>:<div className="wfm-table-wrap"><table className="wfm-table"><thead><tr><th>Reported</th><th>WO</th><th>Reason</th><th>Details</th><th>Location</th><th>Action</th></tr></thead><tbody>{exceptions.map(x=><tr key={x.id}><td>{new Date(x.reportedAt).toLocaleString()}</td><td><b>{x.workOrder?.woNumber||x.workOrderId}</b><small>{x.workOrder?.type} • {x.workOrder?.status}</small></td><td>{x.reason.replaceAll('_',' ')}</td><td>{x.notes||'—'}</td><td>{x.lat!=null&&x.lng!=null?`${Number(x.lat).toFixed(5)}, ${Number(x.lng).toFixed(5)}`:'Not captured'}</td><td><button disabled={busy} onClick={()=>{setReviewing(x);setResolution('RESUME');setReviewNote('');setError('')}} className="wfm-primary-btn">Review</button></td></tr>)}</tbody></table></div>}
 {reviewing&&<div className="wfm-review-panel"><div className="wfm-section-title"><div><h3>Review {reviewing.workOrder?.woNumber||reviewing.workOrderId}</h3><div className="wfm-copy">{reviewing.reason.replaceAll('_',' ')} • reported {new Date(reviewing.reportedAt).toLocaleString()}</div></div><button disabled={busy} onClick={()=>setReviewing(null)} className="wfm-secondary-btn">Close</button></div><div className="wfm-info"><b>Technician notes:</b> {reviewing.notes||'No notes supplied.'}<br/><b>Captured GPS:</b> {reviewing.lat!=null&&reviewing.lng!=null?`${reviewing.lat}, ${reviewing.lng}`:'Not available'}</div><label>Management resolution</label><div className="wfm-toolbar">{RESOLUTIONS.map(r=><button key={r.value} disabled={busy} onClick={()=>setResolution(r.value)} className={resolution===r.value?(r.danger?'wfm-danger-btn':'wfm-primary-btn'):'wfm-secondary-btn'}>{r.label}</button>)}</div><div className="wfm-info">{RESOLUTIONS.find(r=>r.value===resolution)?.help}</div><label>Management note {resolution==='KEEP_ON_HOLD'||resolution==='CANCEL'?'(required)':'(optional)'}</label><textarea value={reviewNote} onChange={e=>setReviewNote(e.target.value)} rows={4} placeholder="Decision notes / instructions for field operations"/><div className="wfm-alert">This action changes operational state immediately. Concurrent duplicate reviews are rejected server-side and every accepted decision is audited.</div><button disabled={busy} onClick={reviewException} className={resolution==='CANCEL'?'wfm-danger-btn':'wfm-primary-btn'}>{busy?'Processing…':`Confirm ${RESOLUTIONS.find(r=>r.value===resolution)?.label}`}</button></div>}</section>
 <section className="wfm-grid-2"><div className="wfm-panel"><div className="wfm-eyebrow">MANAGEMENT CONTROL</div><h3>Dispatch Control</h3><p className="wfm-copy">Assignment is explicit. DRAFT or ASSIGNED work orders can be assigned/reassigned only while no execution is active.</p><label>Work order</label><select value={selectedWoId} onChange={e=>{setSelectedWoId(e.target.value);const w=workOrders.find(x=>x.id===e.target.value);setSelectedTeamId(w?.assignments?.[0]?.teamId||'');setExpectedTeamId(w?.assignments?.[0]?.teamId||null)}}><option value="">Select work order</option>{workOrders.filter(w=>w.status==='DRAFT'||w.status==='ASSIGNED').map(w=><option key={w.id} value={w.id}>{w.woNumber} • {w.status} • {w.type}</option>)}</select><label>Team</label><select value={selectedTeamId} onChange={e=>setSelectedTeamId(e.target.value)}><option value="">Select team</option>{teams.filter(t=>t.activeTechnicians>0).map(t=><option key={t.id} value={t.id}>{t.name} • {t.activeTechnicians} active tech(s)</option>)}</select><button disabled={busy||!selectedWoId||!selectedTeamId} onClick={assign} className="wfm-primary-btn">{selectedWo?.status==='ASSIGNED'?'Confirm Reassignment':'Assign Team'}</button><p className="wfm-info">No automatic reassignment is performed. Every change is initiated by management and audited server-side.</p></div><div className="wfm-panel"><div className="wfm-eyebrow">LOCATION INTELLIGENCE</div><h3>Technician Proximity & Smart Next</h3><select value={technicianId} onChange={e=>{setTechnicianId(e.target.value);setNearby([]);setSmartNext(null);setRoute(null)}}><option value="">Select technician</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.name||t.id} • {t.status||'UNKNOWN'}</option>)}</select><div className="wfm-toolbar"><button disabled={!technicianId||busy} onClick={findNearby} className="wfm-secondary-btn">Nearby ≤3 km</button><button disabled={!technicianId||busy} onClick={suggestNext} className="wfm-secondary-btn">Suggest Smart Next</button><button disabled={!technicianId||busy} onClick={optimizeRoute} className="wfm-secondary-btn">Route Preview</button></div><p className="wfm-info">Smart Next and route optimization are suggestions only. They do not reorder or reassign work orders.</p>{smartNext&&<pre className="wfm-code">Smart Next: {JSON.stringify(smartNext,null,2)}</pre>}{nearby.length>0&&<div>{nearby.slice(0,10).map((t:any)=><div key={t.id} className="wfm-route-row"><b>{t.name||t.id}</b> • {t.distance_m}m • {t.status} {t.isStale?'• stale location':''}</div>)}</div>}</div></section>
 {route&&<section className="wfm-panel"><div className="wfm-eyebrow">PREVIEW ONLY</div><h3>Route Preview</h3><p className="wfm-copy">Job Controller retains dispatch control.</p>{(route.summary?.stops||[]).map((s:any,i:number)=><div key={`${s.woNumber}-${i}`} className="wfm-route-row"><b>#{i+1} {s.woNumber}</b> • {s.distance_m}m • {s.estimatedMinutes}min</div>)}</section>}
 <section className="wfm-panel"><div className="wfm-section-title"><div><div className="wfm-eyebrow">CURRENT OPERATIONS</div><h3>Work Order Queue</h3></div><span className="wfm-control-pill">{workOrders.length} work orders</span></div><div className="wfm-table-wrap"><table className="wfm-table"><thead><tr><th>WO</th><th>Type</th><th>Status</th><th>Assigned Team</th></tr></thead><tbody>{workOrders.slice(0,100).map(w=><tr key={w.id}><td><b>{w.woNumber}</b></td><td>{w.type}</td><td>{w.status}</td><td>{teams.find(t=>t.id===w.assignments?.[0]?.teamId)?.name||'—'}</td></tr>)}</tbody></table></div></section></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <main className="wfm-page">{children}</main>}
function Metric({label,value}:{label:string;value:any}){return <div className="wfm-kpi"><span>{label}</span><strong>{String(value)}</strong></div>}
