'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { apiJson, clearSession, downloadAuthenticated, loadSession, login, Session } from '../lib/api';

type WorkOrder={id:string;woNumber:string;type:string;status:string;subscriberName?:string;subscriber?:{name?:string;address?:string};assignments?:{teamId:string}[]};
type Technician={id:string;name?:string;status?:string;lastLat?:number|null;lastLng?:number|null;lastLocationAt?:string|null};
type Team={id:string;name:string;activeTechnicians:number;technicians:Technician[]};

export default function ManagementPortal(){
 const[session,setSession]=useState<Session|null>(null),[booting,setBooting]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[range,setRange]=useState('monthly');
 const[report,setReport]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null),[network,setNetwork]=useState<any>(null),[workOrders,setWorkOrders]=useState<WorkOrder[]>([]),[teams,setTeams]=useState<Team[]>([]),[technicianId,setTechnicianId]=useState(''),[route,setRoute]=useState<any>(null);
 const[selectedWoId,setSelectedWoId]=useState(''),[selectedTeamId,setSelectedTeamId]=useState(''),[nearby,setNearby]=useState<any[]>([]),[smartNext,setSmartNext]=useState<any>(null);
 useEffect(()=>{setSession(loadSession());setBooting(false)},[]);
 async function refresh(active:Session,selectedRange=range){setError('');try{const[r,a,w,n,t]=await Promise.all([apiJson(`/reports/summary?range=${selectedRange}`,{},active),apiJson(`/phase4/analytics/advanced?range=${selectedRange}`,{},active),apiJson('/work-orders',{},active),apiJson('/phase4/network/health',{},active),apiJson('/work-orders/dispatch/teams',{},active)]);setReport(r);setAnalytics(a);setWorkOrders(w.data||[]);setNetwork(n);setTeams(t.teams||[])}catch(e:any){setError(e.message||'Unable to load management data');if(e.message==='Session expired'||e.message==='AUTH_REQUIRED')setSession(null)}}
 useEffect(()=>{if(session)refresh(session,range)},[session,range]);
 async function submitLogin(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await login(email,password);setSession(s);setPassword('')}catch(e:any){setError(e.message||'Login failed')}finally{setBusy(false)}}
 function logout(){clearSession();setSession(null);setReport(null);setWorkOrders([]);setTeams([])}
 const technicians=useMemo(()=>teams.flatMap(t=>t.technicians||[]).filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i),[teams]);
 const selectedWo=workOrders.find(w=>w.id===selectedWoId);
 async function assign(){if(!selectedWoId||!selectedTeamId)return;setBusy(true);setError('');setNotice('');try{const result=await apiJson(`/work-orders/${selectedWoId}/assign`,{method:'POST',body:JSON.stringify({teamId:selectedTeamId})},session);setNotice(result.idempotent?'Assignment already current. No duplicate change was made.':selectedWo?.status==='ASSIGNED'?'Work order reassigned. Previous assignment was replaced and audited.':'Work order assigned and audited.');await refresh(session!,range)}catch(e:any){setError(e.message||'Assignment failed')}finally{setBusy(false)}}
 async function findNearby(){const tech=technicians.find(t=>t.id===technicianId);if(!tech||tech.lastLat==null||tech.lastLng==null){setError('Selected technician has no usable last-known location.');return}setBusy(true);setError('');try{const data=await apiJson(`/work-orders/nearby?lat=${tech.lastLat}&lng=${tech.lastLng}&radius=3000`,{},session);setNearby(data||[])}catch(e:any){setError(e.message||'Nearby lookup failed')}finally{setBusy(false)}}
 async function suggestNext(){const tech=technicians.find(t=>t.id===technicianId);if(!tech||tech.lastLat==null||tech.lastLng==null){setError('Selected technician has no usable last-known location.');return}setBusy(true);setError('');try{setSmartNext(await apiJson(`/work-orders/smart-next?technicianId=${encodeURIComponent(tech.id)}&lat=${tech.lastLat}&lng=${tech.lastLng}`,{},session))}catch(e:any){setError(e.message||'Smart Next failed')}finally{setBusy(false)}}
 async function optimizeRoute(){if(!technicianId){setError('Select a technician first.');return}setBusy(true);setError('');try{setRoute(await apiJson(`/phase4/route/optimize?technicianId=${encodeURIComponent(technicianId)}&date=${new Date().toISOString().slice(0,10)}`,{},session))}catch(e:any){setError(e.message||'Route optimization failed')}finally{setBusy(false)}}
 if(booting)return <Shell><Card>Loading secure management portal…</Card></Shell>;
 if(!session)return <Shell><div style={{maxWidth:430,margin:'8vh auto'}}><Card><h1 style={{color:'#F59E0B'}}>FiberBlaze WFM</h1><p style={muted}>Management Portal • Authorized access only</p><form onSubmit={submitLogin} style={{display:'grid',gap:12}}><input required type="email" placeholder="Work email" value={email} onChange={e=>setEmail(e.target.value)} style={input}/><input required type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} style={input}/>{error&&<div style={errorBox}>{error}</div>}<button disabled={busy} style={primary}>{busy?'Signing in…':'Sign in'}</button></form><p style={small}>Job Controller, Supervisor, and Administrator accounts only.</p></Card></div></Shell>;
 return <Shell>
  <header style={header}><div><h1 style={{margin:0,color:'#F59E0B'}}>FiberBlaze WFM — Management</h1><div style={muted}>Authenticated operations portal • {session.user.role}</div></div><div><span style={{fontSize:12,marginRight:8}}>{session.user.name||session.user.email}</span><button onClick={logout} style={secondary}>Sign out</button></div></header>
  {error&&<div style={{...errorBox,marginBottom:10}}>{error}</div>}{notice&&<div style={{...noticeBox,marginBottom:10}}>{notice}</div>}
  <div style={toolbar}>{['daily','weekly','monthly'].map(r=><button key={r} onClick={()=>setRange(r)} style={range===r?primary:secondary}>{r.toUpperCase()}</button>)}<button onClick={()=>downloadAuthenticated(`/reports/export?format=excel&range=${range}`,`fiberblaze-${range}.xlsx`,session)} style={secondary}>Export Excel</button><button onClick={()=>window.print()} style={secondary}>Print</button></div>
  <section style={grid4}><Metric label="Total WOs" value={report?.totals?.total??0}/><Metric label="Completed" value={report?.totals?.completed??0}/><Metric label="FB-Issue" value={report?.totals?.fbIssue??0}/><Metric label="CUST-Issue" value={report?.totals?.custIssue??0}/></section>
  <section style={grid2}>
   <Card><h3>Dispatch Control</h3><p style={muted}>Assignment is explicit. DRAFT or ASSIGNED work orders can be assigned/reassigned only while no execution is active.</p><label style={small}>Work order</label><select value={selectedWoId} onChange={e=>{setSelectedWoId(e.target.value);const w=workOrders.find(x=>x.id===e.target.value);setSelectedTeamId(w?.assignments?.[0]?.teamId||'')}} style={input}><option value="">Select work order</option>{workOrders.filter(w=>w.status==='DRAFT'||w.status==='ASSIGNED').map(w=><option key={w.id} value={w.id}>{w.woNumber} • {w.status} • {w.type}</option>)}</select><label style={small}>Team</label><select value={selectedTeamId} onChange={e=>setSelectedTeamId(e.target.value)} style={input}><option value="">Select team</option>{teams.filter(t=>t.activeTechnicians>0).map(t=><option key={t.id} value={t.id}>{t.name} • {t.activeTechnicians} active tech(s)</option>)}</select><button disabled={busy||!selectedWoId||!selectedTeamId} onClick={assign} style={{...primary,marginTop:10}}>{selectedWo?.status==='ASSIGNED'?'Confirm Reassignment':'Assign Team'}</button><p style={small}>No automatic reassignment is performed. Every change is initiated by management and audited server-side.</p></Card>
   <Card><h3>Technician Proximity & Smart Next</h3><select value={technicianId} onChange={e=>{setTechnicianId(e.target.value);setNearby([]);setSmartNext(null);setRoute(null)}} style={input}><option value="">Select technician</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.name||t.id} • {t.status||'UNKNOWN'}</option>)}</select><div style={toolbar}><button disabled={!technicianId||busy} onClick={findNearby} style={secondary}>Nearby ≤3 km</button><button disabled={!technicianId||busy} onClick={suggestNext} style={secondary}>Suggest Smart Next</button><button disabled={!technicianId||busy} onClick={optimizeRoute} style={secondary}>Route Preview</button></div><p style={small}>Smart Next and route optimization are suggestions only. They do not reorder or reassign work orders.</p>{smartNext&&<pre style={pre}>Smart Next: {JSON.stringify(smartNext,null,2)}</pre>}{nearby.length>0&&<div>{nearby.slice(0,10).map((t:any)=><div key={t.id} style={row}><b>{t.name||t.id}</b> • {t.distance_m}m • {t.status} {t.isStale?'• stale location':''}</div>)}</div>}</Card>
  </section>
  {route&&<section style={{marginTop:12}}><Card><h3>Route Preview</h3><p style={small}>Preview only — Job Controller retains dispatch control.</p>{(route.summary?.stops||[]).map((s:any,i:number)=><div key={`${s.woNumber}-${i}`} style={row}><b>#{i+1} {s.woNumber}</b> • {s.distance_m}m • {s.estimatedMinutes}min</div>)}</Card></section>}
  <section style={{marginTop:12}}><Card><h3>Work Order Queue</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th style={th}>WO</th><th style={th}>Type</th><th style={th}>Status</th><th style={th}>Assigned Team</th></tr></thead><tbody>{workOrders.slice(0,100).map(w=><tr key={w.id}><td style={td}>{w.woNumber}</td><td style={td}>{w.type}</td><td style={td}>{w.status}</td><td style={td}>{teams.find(t=>t.id===w.assignments?.[0]?.teamId)?.name||'—'}</td></tr>)}</tbody></table></div></Card></section>
 </Shell>
}
function Shell({children}:{children:React.ReactNode}){return <main style={{padding:20,background:'#0A0A0B',minHeight:'100vh',color:'#fff',fontFamily:'Inter,system-ui'}}>{children}</main>};function Card({children}:{children:React.ReactNode}){return <div style={{background:'#18181B',border:'1px solid #27272A',borderRadius:14,padding:16}}>{children}</div>};function Metric({label,value}:{label:string,value:any}){return <Card><div style={{fontSize:28,fontWeight:800}}>{value}</div><div style={small}>{label}</div></Card>}
const grid4:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10},grid2:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:12,marginTop:12},header:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginBottom:16},toolbar:React.CSSProperties={display:'flex',gap:8,flexWrap:'wrap',margin:'10px 0'},input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:'10px 12px',margin:'5px 0 10px',borderRadius:9,border:'1px solid #3F3F46',background:'#09090B',color:'#fff'},primary:React.CSSProperties={padding:'9px 13px',borderRadius:9,border:0,background:'#F59E0B',color:'#000',fontWeight:800,cursor:'pointer'},secondary:React.CSSProperties={padding:'9px 13px',borderRadius:9,border:'1px solid #3F3F46',background:'#27272A',color:'#fff',fontWeight:700,cursor:'pointer'},errorBox:React.CSSProperties={padding:10,borderRadius:9,border:'1px solid #EF4444',background:'#450A0A',color:'#FCA5A5',fontSize:12},noticeBox:React.CSSProperties={padding:10,borderRadius:9,border:'1px solid #22C55E',background:'#052E16',color:'#86EFAC',fontSize:12},muted:React.CSSProperties={fontSize:12,color:'#A1A1AA'},small:React.CSSProperties={fontSize:11,color:'#A1A1AA'},th:React.CSSProperties={textAlign:'left',padding:'8px 6px',borderBottom:'1px solid #3F3F46',color:'#A1A1AA'},td:React.CSSProperties={padding:'8px 6px',borderBottom:'1px solid #27272A'},row:React.CSSProperties={padding:'8px 0',borderBottom:'1px solid #27272A',fontSize:12},pre:React.CSSProperties={whiteSpace:'pre-wrap',fontSize:10,background:'#09090B',padding:8,borderRadius:8,maxHeight:180,overflow:'auto'};
