'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiJson, loadSession, Session } from '../../lib/api';

type Api={name:string;description:string;status:string};
type Architecture={architecture:string;benefits:string;preparedApis:Api[];currentIntegration:string};
type Pending={pending:number;jobs:any[]};

export default function Integrations(){
 const[session,setSession]=useState<Session|null>(null),[arch,setArch]=useState<Architecture|null>(null),[pending,setPending]=useState<Pending|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const[form,setForm]=useState({source:'WFM',target:'',payload:'{}'});
 useEffect(()=>setSession(loadSession()),[]);
 async function load(){if(!session)return;setLoading(true);setError('');try{setArch(await apiJson('/integration/architecture',{},session));if(session.user.role==='ADMINISTRATOR'){try{setPending(await apiJson('/integration/pending',{},session))}catch{setPending(null)}}}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(session&&['SUPERVISOR','ADMINISTRATOR'].includes(session.user.role))load();else if(session)setLoading(false)},[session]);
 async function queue(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{let payload:any;try{payload=JSON.parse(form.payload)}catch{throw new Error('Payload must be valid JSON.')}await apiJson('/integration/queue',{method:'POST',body:JSON.stringify({source:form.source.trim(),target:form.target.trim(),payload})},session);setMessage('Integration job queued successfully.');setForm(x=>({...x,target:'',payload:'{}'}));if(session?.user.role==='ADMINISTRATOR')await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!session)return <div className="wfm-page"><div className="wfm-panel"><h2>Integrations</h2><p>Sign in through Command Center first.</p></div></div>;
 if(!['SUPERVISOR','ADMINISTRATOR'].includes(session.user.role))return <div className="wfm-page"><div className="wfm-panel"><span className="wfm-eyebrow">INTEGRATION LAYER</span><h2>Integrations</h2><div className="wfm-alert">Supervisor or Administrator access is required for integration management.</div></div></div>;
 return <div className="wfm-page">
  <div className="wfm-page-head"><div><span className="wfm-eyebrow">FUTURE-READY API GATEWAY</span><h1>Integrations</h1><p>Keep technician and management clients behind the WFM API while external FiberBlaze and Meridian systems connect through one controlled integration layer.</p></div><button className="wfm-layer-toggle on" onClick={load} disabled={loading}>{loading?'REFRESHING…':'REFRESH'}</button></div>
  {error&&<div className="wfm-alert">{error}</div>}{message&&<div className="wfm-info"><b>{message}</b></div>}
  <div className="wfm-kpis"><K label="Prepared APIs" v={arch?.preparedApis?.filter(x=>x.status==='PREPARED').length||0}/><K label="Planned APIs" v={arch?.preparedApis?.filter(x=>x.status==='PLANNED').length||0}/><K label="Pending Jobs" v={pending?.pending??'ADMIN ONLY'}/><K label="Client Architecture" v="WFM GATEWAY"/></div>
  <div className="wfm-panel"><div className="wfm-section-title"><div><span className="wfm-eyebrow">ARCHITECTURE</span><h3>Central Integration Gateway</h3></div><span className="wfm-control-pill">DECOUPLED CLIENTS</span></div>{loading?<div className="wfm-empty">Loading integration architecture…</div>:<><div className="wfm-info"><b>{arch?.architecture||'WFM integration architecture unavailable.'}</b><br/>{arch?.benefits}</div><div className="wfm-route-row"><span className="wfm-route-number">✓</span><div><b>Current integration rule</b><small>{arch?.currentIntegration}</small></div></div></>}</div>
  <div className="wfm-grid-2"><div className="wfm-panel"><span className="wfm-eyebrow">CONNECTOR ROADMAP</span><h3>Prepared External APIs</h3>{arch?.preparedApis?.length?arch.preparedApis.map((a,i)=><div className="wfm-route-row" key={a.name}><span className="wfm-route-number">{i+1}</span><div><b>{a.name}</b><small>{a.description}</small></div><span className={`wfm-badge ${a.status==='PREPARED'?'smart':'assigned'}`}>{a.status}</span></div>):<div className="wfm-empty">No prepared API definitions returned.</div>}</div>
   <div className="wfm-panel"><span className="wfm-eyebrow">CONTROLLED QUEUE</span><h3>Queue Integration Job</h3><form onSubmit={queue}><label>Source system</label><input required value={form.source} onChange={e=>setForm(x=>({...x,source:e.target.value}))}/><label>Target system</label><input required value={form.target} onChange={e=>setForm(x=>({...x,target:e.target.value}))} placeholder="Example: BILLING"/><label>Payload (JSON)</label><textarea required rows={6} value={form.payload} onChange={e=>setForm(x=>({...x,payload:e.target.value}))}/><button disabled={busy}>{busy?'Queueing…':'Queue Integration Job'}</button></form><div className="wfm-info">This queues a WFM integration record; it does not connect directly to an external provider. Production delivery can later use webhooks, a message queue or provider-specific adapters.</div></div></div>
  {session.user.role==='ADMINISTRATOR'&&<div className="wfm-panel"><div className="wfm-section-title"><div><span className="wfm-eyebrow">ADMINISTRATOR</span><h3>Pending Integration Jobs</h3></div><span className="wfm-control-pill">{pending?.pending||0} PENDING</span></div>{pending?.jobs?.length?pending.jobs.map((j:any,i:number)=><div className="wfm-route-row" key={j.id||i}><span className="wfm-route-number">{i+1}</span><div><b>{j.sourceSystem||'UNKNOWN'} → {j.targetSystem||'UNKNOWN'}</b><small>{j.id||'Integration job'} • {j.status||'PENDING'}</small></div><span className="wfm-badge on-hold">{j.status||'PENDING'}</span></div>):<div className="wfm-empty">No pending integration jobs.</div>}</div>}
 </div>
}
function K({label,v}:{label:string;v:number|string}){return <div className="wfm-kpi"><span>{label}</span><strong>{v}</strong></div>}
