'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { apiJson, loadSession, Session } from '../../lib/api';

type User={id:string;name:string;email:string;phone?:string|null;role:string;teamId?:string|null;status:string;isActive:boolean;createdAt:string};
type Team={id:string;name:string;activeTechnicians?:number;technicians?:{id:string;name?:string;status?:string}[]};
const ROLES=['TECHNICIAN','JOB_CONTROLLER','SUPERVISOR','ADMINISTRATOR'];

export default function UsersTeams(){
 const[session,setSession]=useState<Session|null>(null),[users,setUsers]=useState<User[]>([]),[teams,setTeams]=useState<Team[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[q,setQ]=useState('');
 const[form,setForm]=useState({name:'',email:'',password:'',role:'TECHNICIAN',phone:'',teamId:''});
 useEffect(()=>setSession(loadSession()),[]);
 async function load(){if(!session)return;setLoading(true);setError('');try{const u=await apiJson('/users',{},session);setUsers(u.users||[]);try{const t=await apiJson('/work-orders/dispatch/teams',{},session);setTeams(t.teams||[])}catch{setTeams([])}}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(session)load()},[session]);
 async function create(e:FormEvent){e.preventDefault();setBusy('create');setError('');try{await apiJson('/users',{method:'POST',body:JSON.stringify({...form,teamId:form.teamId||undefined,phone:form.phone||undefined})},session);setForm({name:'',email:'',password:'',role:'TECHNICIAN',phone:'',teamId:''});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function toggle(u:User){setBusy(u.id);setError('');try{await apiJson(`/users/${encodeURIComponent(u.id)}/status`,{method:'PATCH',body:JSON.stringify({isActive:!u.isActive})},session);await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const filtered=useMemo(()=>users.filter(u=>!q||`${u.name} ${u.email} ${u.role} ${u.status}`.toLowerCase().includes(q.toLowerCase())),[users,q]);
 if(!session)return <div className="wfm-page"><div className="wfm-panel"><h2>Users & Teams</h2><p>Sign in through Command Center first.</p></div></div>;
 if(session.user.role!=='ADMINISTRATOR')return <div className="wfm-page"><div className="wfm-panel"><span className="wfm-eyebrow">ADMINISTRATION</span><h2>Users & Teams</h2><div className="wfm-alert">Administrator access is required to manage user accounts.</div></div></div>;
 const active=users.filter(x=>x.isActive).length,techs=users.filter(x=>x.role==='TECHNICIAN').length,online=users.filter(x=>x.role==='TECHNICIAN'&&x.status!=='OFFLINE').length;
 return <div className="wfm-page">
  <div className="wfm-page-head"><div><span className="wfm-eyebrow">ACCESS + FIELD ORGANIZATION</span><h1>Users & Teams</h1><p>Manage WFM accounts, operational roles, technician availability and team membership.</p></div><button className="wfm-layer-toggle on" onClick={load} disabled={loading}>{loading?'REFRESHING…':'REFRESH'}</button></div>
  {error&&<div className="wfm-alert">{error}</div>}
  <div className="wfm-kpis"><K label="Users" v={users.length}/><K label="Active Accounts" v={active}/><K label="Technicians" v={techs}/><K label="Online Technicians" v={online}/><K label="Field Teams" v={teams.length}/></div>
  <div className="wfm-grid-2"><div className="wfm-panel"><span className="wfm-eyebrow">ADMINISTRATOR</span><h3>Create WFM User</h3><form onSubmit={create}><label>Name</label><input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/><label>Email</label><input required type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))}/><label>Password</label><input required minLength={12} type="password" value={form.password} onChange={e=>setForm(x=>({...x,password:e.target.value}))} placeholder="Minimum 12 characters"/><label>Role</label><select value={form.role} onChange={e=>setForm(x=>({...x,role:e.target.value}))}>{ROLES.map(r=><option key={r}>{r}</option>)}</select><label>Team</label><select value={form.teamId} onChange={e=>setForm(x=>({...x,teamId:e.target.value}))}><option value="">No team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><label>Phone</label><input value={form.phone} onChange={e=>setForm(x=>({...x,phone:e.target.value}))}/><button disabled={busy==='create'}>{busy==='create'?'Creating…':'Create User'}</button></form><div className="wfm-info">New accounts are created OFFLINE and active. Passwords require at least 12 characters.</div></div>
   <div className="wfm-panel"><span className="wfm-eyebrow">FIELD ORGANIZATION</span><h3>Teams</h3>{teams.length?teams.map((t,i)=><div className="wfm-route-row" key={t.id}><span className="wfm-route-number">{i+1}</span><div><b>{t.name}</b><small>{t.activeTechnicians??t.technicians?.filter(x=>x.status!=='OFFLINE').length??0} active technician(s) • {t.technicians?.length??0} listed</small></div></div>):<div className="wfm-empty">No teams returned by the dispatch service.</div>}</div></div>
  <div className="wfm-panel"><div className="wfm-section-title"><div><span className="wfm-eyebrow">ACCOUNT DIRECTORY</span><h3>WFM Users</h3></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search user, email, role or status"/></div>{loading?<div className="wfm-empty">Loading users…</div>:<div className="wfm-table-wrap"><table className="wfm-table"><thead><tr><th>User</th><th>Role</th><th>Team</th><th>Field Status</th><th>Account</th><th>Action</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><b>{u.name}</b><small>{u.email}{u.phone?` • ${u.phone}`:''}</small></td><td>{u.role.replaceAll('_',' ')}</td><td>{teams.find(t=>t.id===u.teamId)?.name||'—'}</td><td><span className={`wfm-badge ${u.status==='WORKING'?'working':'assigned'}`}>{u.status}</span></td><td><span className={`wfm-badge ${u.isActive?'smart':'on-hold'}`}>{u.isActive?'ACTIVE':'DISABLED'}</span></td><td><button disabled={busy===u.id||u.id===session.user.id} onClick={()=>toggle(u)}>{busy===u.id?'Working…':u.isActive?'Disable':'Enable'}</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="wfm-empty">No users match this search.</div>}</div>}</div>
 </div>
}
function K({label,v}:{label:string;v:number}){return <div className="wfm-kpi"><span>{label}</span><strong>{v}</strong></div>}
