'use client';
import { useCallback, useEffect, useState } from 'react';
import { apiJson, loadSession, Session } from '../../lib/api';

type Counts={draft:number;assigned:number;working:number;onHold:number;completed:number;fbIssue:number;custIssue:number;cancelled:number;pendingExceptions:number;activeExecutions:number;activeTechnicians:number;availableTechnicians:number;staleLocations:number;attentionItems:number};
type Tech={id:string;name:string;teamId?:string|null;status?:string|null;location?:{lat:number;lng:number;capturedAt?:string|null;isStale:boolean}|null;activeWorkOrder?:{id:string;woNumber:string;type:string;status:string;startedAt:string}|null};
type Attention={kind:string;severity:'HIGH'|'MEDIUM';technicianId?:string|null;technicianName?:string|null;workOrderNumber?:string|null;since?:string|null;message:string};
type Snapshot={generatedAt:string;source:string;refreshRecommendedSeconds:number;thresholds:{staleLocationSeconds:number;longRunningJobMinutes:number;agingExceptionMinutes:number};counts:Counts;attention:Attention[];technicians:Tech[];activeExecutions:any[];pendingExceptions:any[]};
const card:React.CSSProperties={background:'#18181B',border:'1px solid #27272A',borderRadius:14,padding:14};const muted:React.CSSProperties={color:'#A1A1AA',fontSize:12};const td:React.CSSProperties={padding:'10px 8px',borderTop:'1px solid #27272A',textAlign:'left',verticalAlign:'top'};
export default function LiveOperationsPage(){
 const[session,setSession]=useState<Session|null>(null),[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);useEffect(()=>{setSession(loadSession())},[]);
 const refresh=useCallback(async(active:Session)=>{try{setError('');setData(await apiJson<Snapshot>('/phase4/operations/live',{},active))}catch(e:any){setError(e.message||'Unable to load live operations')}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!session){setLoading(false);return}refresh(session);const timer=setInterval(()=>refresh(session),15000);return()=>clearInterval(timer)},[session,refresh]);
 if(!session)return <main style={{padding:24,background:'#0A0A0B',minHeight:'100vh',color:'#fff'}}><div style={card}><h2>Live Operations Board</h2><p style={muted}>Sign in through the Management Portal first, then return to this board.</p><a href="/" style={{color:'#F59E0B'}}>Open Management Portal</a></div></main>;
 const c=data?.counts;return <main style={{padding:20,background:'#0A0A0B',minHeight:'100vh',color:'#fff',fontFamily:'Arial,sans-serif'}}><header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h1 style={{margin:0,color:'#F59E0B'}}>Live Operations Board</h1><div style={muted}>Authoritative field operations • automatic refresh every 15 seconds</div></div><div><a href="/" style={{color:'#F59E0B',marginRight:12}}>Management Portal</a><button onClick={()=>session&&refresh(session)} style={{padding:'9px 12px',borderRadius:8,border:'1px solid #52525B',background:'#27272A',color:'#fff'}}>Refresh now</button></div></header>{error&&<div style={{marginTop:12,padding:12,borderRadius:10,background:'#450A0A',color:'#FCA5A5'}}>{error}</div>}{loading&&!data?<p>Loading operational snapshot…</p>:<>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,marginTop:16}}><Metric label="Needs Attention" value={c?.attentionItems}/><Metric label="Working" value={c?.working}/><Metric label="On Hold" value={c?.onHold}/><Metric label="Assigned" value={c?.assigned}/><Metric label="Draft / Unassigned" value={c?.draft}/><Metric label="Pending Exceptions" value={c?.pendingExceptions}/><Metric label="Available Techs" value={c?.availableTechnicians}/><Metric label="Stale / Missing GPS" value={c?.staleLocations}/></section>
 <section style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Operations Attention Queue</h3><p style={muted}>Advisory only — no work order is automatically reassigned or rearranged. Thresholds: GPS {data?.thresholds?.staleLocationSeconds||120}s, active job {data?.thresholds?.longRunningJobMinutes||120}min, pending exception {data?.thresholds?.agingExceptionMinutes||30}min.</p>{!data?.attention?.length?<p style={{color:'#86EFAC',fontSize:12}}>No threshold-based attention items.</p>:data.attention.map((a,i)=><div key={`${a.kind}-${a.technicianId||''}-${a.workOrderNumber||''}-${i}`} style={{padding:'10px 0',borderTop:'1px solid #27272A'}}><b style={{color:a.severity==='HIGH'?'#FCA5A5':'#FDE68A'}}>{a.severity} • {a.kind.replaceAll('_',' ')}</b>{a.workOrderNumber&&<> • <b>{a.workOrderNumber}</b></>}<div style={{fontSize:12,marginTop:3}}>{a.message}</div><div style={muted}>{a.technicianName||'Operations capacity'}{a.since?` • since ${new Date(a.since).toLocaleString()}`:''}</div></div>)}</section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(420px,1fr))',gap:12,marginTop:12}}><div style={card}><h3 style={{marginTop:0}}>Technician Live Status</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th style={td}>Technician</th><th style={td}>Status</th><th style={td}>Active WO</th><th style={td}>Location</th></tr></thead><tbody>{(data?.technicians||[]).map(t=><tr key={t.id}><td style={td}><b>{t.name}</b><div style={muted}>{t.teamId||'No team'}</div></td><td style={td}>{t.status||'UNKNOWN'}</td><td style={td}>{t.activeWorkOrder?<><b>{t.activeWorkOrder.woNumber}</b><div style={muted}>{t.activeWorkOrder.type} • {t.activeWorkOrder.status}</div></>:'—'}</td><td style={td}>{t.location?<><span>{t.location.lat.toFixed(5)}, {t.location.lng.toFixed(5)}</span><div style={{...muted,color:t.location.isStale?'#FCA5A5':'#86EFAC'}}>{t.location.isStale?'STALE':'FRESH'}{t.location.capturedAt?` • ${new Date(t.location.capturedAt).toLocaleTimeString()}`:''}</div></>:'Not reported'}</td></tr>)}</tbody></table></div></div><div style={card}><h3 style={{marginTop:0}}>Pending Exception Queue</h3>{!data?.pendingExceptions?.length?<p style={muted}>No pending field exceptions.</p>:data.pendingExceptions.map(x=><div key={x.id} style={{padding:'10px 0',borderTop:'1px solid #27272A'}}><b>{x.workOrder?.woNumber||x.workOrder?.id}</b> • {String(x.reason).replaceAll('_',' ')}<div style={muted}>{x.technician?.name||x.technician?.id} • {new Date(x.reportedAt).toLocaleString()}</div>{x.notes&&<div style={{marginTop:4,fontSize:12}}>{x.notes}</div>}</div>)}</div></section>
 <section style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Active Work Executions</h3>{!data?.activeExecutions?.length?<p style={muted}>No active executions.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th style={td}>Started</th><th style={td}>WO</th><th style={td}>Type / Status</th><th style={td}>Technician</th><th style={td}>Location freshness</th></tr></thead><tbody>{data.activeExecutions.map(e=><tr key={e.executionId}><td style={td}>{new Date(e.startedAt).toLocaleString()}</td><td style={td}><b>{e.workOrder?.woNumber}</b></td><td style={td}>{e.workOrder?.type} • {e.workOrder?.status}</td><td style={td}>{e.technician?.name||e.technician?.id}</td><td style={td}>{e.technician?.lastLocationAt?new Date(e.technician.lastLocationAt).toLocaleString():'Not reported'}</td></tr>)}</tbody></table></div>}</section><div style={{...muted,marginTop:12}}>Snapshot: {data?.generatedAt?new Date(data.generatedAt).toLocaleString():'—'} • Source: {data?.source||'—'}</div></>}</main>}
function Metric({label,value}:{label:string;value?:number}){return <div style={card}><div style={{color:'#A1A1AA',fontSize:11,textTransform:'uppercase'}}>{label}</div><div style={{fontSize:28,fontWeight:800,marginTop:4}}>{value??0}</div></div>}
