'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiJson, loadSession, Session } from '../../lib/api';

type Counts={draft:number;assigned:number;working:number;onHold:number;completed:number;fbIssue:number;custIssue:number;cancelled:number;pendingExceptions:number;activeExecutions:number;activeTechnicians:number;availableTechnicians:number;staleLocations:number;attentionItems:number};
type Tech={id:string;name:string;teamId?:string|null;status?:string|null;location?:{lat:number;lng:number;capturedAt?:string|null;isStale:boolean}|null;activeWorkOrder?:{id:string;woNumber:string;type:string;status:string;startedAt:string}|null};
type Attention={kind:string;severity:'HIGH'|'MEDIUM';technicianId?:string|null;technicianName?:string|null;workOrderNumber?:string|null;since?:string|null;message:string};
type Snapshot={generatedAt:string;source:string;refreshRecommendedSeconds:number;thresholds:{staleLocationSeconds:number;longRunningJobMinutes:number;agingExceptionMinutes:number};counts:Counts;attention:Attention[];technicians:Tech[];activeExecutions:any[];pendingExceptions:any[]};
type SeverityFilter='ALL'|'HIGH'|'MEDIUM';
const card:React.CSSProperties={background:'#18181B',border:'1px solid #27272A',borderRadius:14,padding:14};const muted:React.CSSProperties={color:'#A1A1AA',fontSize:12};const td:React.CSSProperties={padding:'10px 8px',borderTop:'1px solid #27272A',textAlign:'left',verticalAlign:'top'};const control:React.CSSProperties={background:'#27272A',border:'1px solid #52525B',color:'#fff',padding:'8px 10px',borderRadius:8};
function ageLabel(since?:string|null){if(!since)return 'Current condition';const ms=Math.max(0,Date.now()-new Date(since).getTime());const mins=Math.floor(ms/60000);if(mins<1)return '<1 min';if(mins<60)return `${mins} min`;const h=Math.floor(mins/60),m=mins%60;return m?`${h}h ${m}m`:`${h}h`}
function ageMs(since?:string|null){return since?Math.max(0,Date.now()-new Date(since).getTime()):0}
export default function LiveOperationsPage(){
 const[session,setSession]=useState<Session|null>(null),[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[severity,setSeverity]=useState<SeverityFilter>('ALL'),[kind,setKind]=useState('ALL'),[technician,setTechnician]=useState('ALL');useEffect(()=>{setSession(loadSession())},[]);
 const refresh=useCallback(async(active:Session)=>{try{setError('');setData(await apiJson<Snapshot>('/phase4/operations/live',{},active))}catch(e:any){setError(e.message||'Unable to load live operations')}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!session){setLoading(false);return}refresh(session);const timer=setInterval(()=>refresh(session),15000);return()=>clearInterval(timer)},[session,refresh]);
 const kinds=useMemo(()=>Array.from(new Set((data?.attention||[]).map(a=>a.kind))).sort(),[data]);const attentionTechs=useMemo(()=>Array.from(new Map((data?.attention||[]).filter(a=>a.technicianId).map(a=>[a.technicianId!,a.technicianName||a.technicianId!])).entries()).sort((a,b)=>a[1].localeCompare(b[1])),[data]);
 const filteredAttention=useMemo(()=>(data?.attention||[]).filter(a=>(severity==='ALL'||a.severity===severity)&&(kind==='ALL'||a.kind===kind)&&(technician==='ALL'||a.technicianId===technician)).sort((a,b)=>{const severityRank=(x:Attention)=>x.severity==='HIGH'?0:1;return severityRank(a)-severityRank(b)||ageMs(b.since)-ageMs(a.since)}),[data,severity,kind,technician]);
 function jumpTo(a:Attention){const target=a.kind.includes('EXCEPTION')?'pending-exceptions':a.technicianId?'technician-status':'active-executions';document.getElementById(target)?.scrollIntoView({behavior:'smooth',block:'start'})}
 if(!session)return <main style={{padding:24,background:'#0A0A0B',minHeight:'100vh',color:'#fff'}}><div style={card}><h2>Live Operations Board</h2><p style={muted}>Sign in through the Management Portal first, then return to this board.</p><a href="/" style={{color:'#F59E0B'}}>Open Management Portal</a></div></main>;
 const c=data?.counts;return <main style={{padding:20,background:'#0A0A0B',minHeight:'100vh',color:'#fff',fontFamily:'Arial,sans-serif'}}><header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h1 style={{margin:0,color:'#F59E0B'}}>Live Operations Board</h1><div style={muted}>Authoritative field operations • automatic refresh every 15 seconds</div></div><div><a href="/" style={{color:'#F59E0B',marginRight:12}}>Management Portal</a><button onClick={()=>session&&refresh(session)} style={control}>Refresh now</button></div></header>{error&&<div style={{marginTop:12,padding:12,borderRadius:10,background:'#450A0A',color:'#FCA5A5'}}>{error}</div>}{loading&&!data?<p>Loading operational snapshot…</p>:<>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,marginTop:16}}><Metric label="Needs Attention" value={c?.attentionItems}/><Metric label="Working" value={c?.working}/><Metric label="On Hold" value={c?.onHold}/><Metric label="Assigned" value={c?.assigned}/><Metric label="Draft / Unassigned" value={c?.draft}/><Metric label="Pending Exceptions" value={c?.pendingExceptions}/><Metric label="Available Techs" value={c?.availableTechnicians}/><Metric label="Stale / Missing GPS" value={c?.staleLocations}/></section>
 <section style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Operations Attention Queue</h3><p style={muted}>Advisory only — no work order is automatically reassigned or rearranged. Critical items are shown before warnings, then oldest first.</p><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'10px 0'}}><select aria-label="Severity filter" value={severity} onChange={e=>setSeverity(e.target.value as SeverityFilter)} style={control}><option value="ALL">All severities</option><option value="HIGH">Critical / High</option><option value="MEDIUM">Warning / Medium</option></select><select aria-label="Alert type filter" value={kind} onChange={e=>setKind(e.target.value)} style={control}><option value="ALL">All alert types</option>{kinds.map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select><select aria-label="Technician filter" value={technician} onChange={e=>setTechnician(e.target.value)} style={control}><option value="ALL">All technicians</option>{attentionTechs.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><span style={{...muted,alignSelf:'center'}}>{filteredAttention.length} of {data?.attention?.length||0} items</span></div><p style={muted}>Thresholds: GPS {data?.thresholds?.staleLocationSeconds||120}s, active job {data?.thresholds?.longRunningJobMinutes||120}min, pending exception {data?.thresholds?.agingExceptionMinutes||30}min. Filters stay selected during automatic refresh.</p>{!filteredAttention.length?<p style={{color:'#86EFAC',fontSize:12}}>No attention items match the current filters.</p>:filteredAttention.map((a,i)=><div key={`${a.kind}-${a.technicianId||''}-${a.workOrderNumber||''}-${i}`} style={{padding:'10px 0',borderTop:'1px solid #27272A'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><b style={{color:a.severity==='HIGH'?'#FCA5A5':'#FDE68A'}}>{a.severity==='HIGH'?'CRITICAL':'WARNING'} • {a.kind.replaceAll('_',' ')}</b>{a.workOrderNumber&&<> • <b>{a.workOrderNumber}</b></>}</div><b style={{color:a.severity==='HIGH'?'#FCA5A5':'#FDE68A'}}>{ageLabel(a.since)}</b></div><div style={{fontSize:12,marginTop:3}}>{a.message}</div><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',flexWrap:'wrap',marginTop:4}}><span style={muted}>{a.technicianName||'Operations capacity'}{a.since?` • since ${new Date(a.since).toLocaleString()}`:''}</span><button onClick={()=>jumpTo(a)} style={{...control,padding:'5px 8px',fontSize:11}}>View related details</button></div></div>)}</section>
 <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(420px,1fr))',gap:12,marginTop:12}}><div id="technician-status" style={card}><h3 style={{marginTop:0}}>Technician Live Status</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th style={td}>Technician</th><th style={td}>Status</th><th style={td}>Active WO</th><th style={td}>Location</th></tr></thead><tbody>{(data?.technicians||[]).map(t=><tr key={t.id}><td style={td}><b>{t.name}</b><div style={muted}>{t.teamId||'No team'}</div></td><td style={td}>{t.status||'UNKNOWN'}</td><td style={td}>{t.activeWorkOrder?<><b>{t.activeWorkOrder.woNumber}</b><div style={muted}>{t.activeWorkOrder.type} • {t.activeWorkOrder.status}</div></>:'—'}</td><td style={td}>{t.location?<><span>{t.location.lat.toFixed(5)}, {t.location.lng.toFixed(5)}</span><div style={{...muted,color:t.location.isStale?'#FCA5A5':'#86EFAC'}}>{t.location.isStale?'STALE':'FRESH'}{t.location.capturedAt?` • ${new Date(t.location.capturedAt).toLocaleTimeString()}`:''}</div></>:'NO GPS REPORTED'}</td></tr>)}</tbody></table></div></div><div id="pending-exceptions" style={card}><h3 style={{marginTop:0}}>Pending Exception Queue</h3>{!data?.pendingExceptions?.length?<p style={muted}>No pending field exceptions.</p>:data.pendingExceptions.map(x=><div key={x.id} style={{padding:'10px 0',borderTop:'1px solid #27272A'}}><b>{x.workOrder?.woNumber||x.workOrder?.id}</b> • {String(x.reason).replaceAll('_',' ')}<div style={muted}>{x.technician?.name||x.technician?.id} • waiting {ageLabel(x.reportedAt)} • {new Date(x.reportedAt).toLocaleString()}</div>{x.notes&&<div style={{marginTop:4,fontSize:12}}>{x.notes}</div>}<a href="/" style={{display:'inline-block',marginTop:6,color:'#F59E0B',fontSize:12}}>Open Management Portal to review</a></div>)}</div></section>
 <section id="active-executions" style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Active Work Executions</h3>{!data?.activeExecutions?.length?<p style={muted}>No active executions.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr><th style={td}>Started</th><th style={td}>Age</th><th style={td}>WO</th><th style={td}>Type / Status</th><th style={td}>Technician</th><th style={td}>Location freshness</th></tr></thead><tbody>{data.activeExecutions.map(e=><tr key={e.executionId}><td style={td}>{new Date(e.startedAt).toLocaleString()}</td><td style={td}><b>{ageLabel(e.startedAt)}</b></td><td style={td}><b>{e.workOrder?.woNumber}</b></td><td style={td}>{e.workOrder?.type} • {e.workOrder?.status}</td><td style={td}>{e.technician?.name||e.technician?.id}</td><td style={td}>{e.technician?.lastLocationAt?`${ageLabel(e.technician.lastLocationAt)} ago`:'NO GPS REPORTED'}</td></tr>)}</tbody></table></div>}</section><div style={{...muted,marginTop:12}}>Snapshot: {data?.generatedAt?new Date(data.generatedAt).toLocaleString():'—'} • Source: {data?.source||'—'}</div></>}</main>}
function Metric({label,value}:{label:string;value?:number}){return <div style={card}><div style={{color:'#A1A1AA',fontSize:11,textTransform:'uppercase'}}>{label}</div><div style={{fontSize:28,fontWeight:800,marginTop:4}}>{value??0}</div></div>}
